language: python
python:
  - 3.6
sudo: required
dist: trusty
addons:
  chrome: stable
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - python -m unittest utests
  - robot -A tests/conf/default.args tests
