language: python
python:
  - 2.7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script:
  - pybot -A tests/conf/default.args tests
