language: python
python:
  - 2.7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
install:
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin
  - ls -al /usr/bin | grep chromedriver
# - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"
# - "export CHROME_BIN=chromium-browser"
 - "export PATH=$PATH:/usr/lib/chromium-browser"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script:
  - pybot -A tests/conf/default.args tests
