language: python
python:
  - 3.6
sudo: required
dist: trusty
addons:
  chrome: stable
services:
  - postgresql
cache: pip
install:
      # install python requirements
      - pip install -r requirements.txt -r requirements-postgres.txt
      - pip install python-coveralls
      - pip install pytest-cov
before_script:
  - psql -c 'create database hub_test;' -U postgres
  - wget "http://chromedriver.storage.googleapis.com/LATEST_RELEASE_76.0.3809/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pytest --cov rfhub/ utests/KeywordTableTest.py -v --cov-config .coveragerc
  - robot -A tests/conf/default.args tests
  - robot -A tests/conf/postgres.args tests
after_success:
  - coveralls