language: python
python:
  - 2.7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
install:
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin
  - ls -al /usr/bin | grep chromedriver
#  - "export CHROME_BIN=chromium-browser"
  - "export PATH=$PATH:/usr/lib/chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - pybot -A tests/conf/default.args tests
