language: python
python:
- '3.6'
- '3.7'
- '3.8'
sudo: required
dist: xenial
services:
  - xvfb
  - postgresql
addons:
  chrome: stable
cache: pip
install:
  - pip install -r requirements.txt -r requirements-postgres.txt
  - pip install coveralls
  - pip install pytest-cov
before_script:
  - psql -c 'create database hub_test;' -U postgres
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - wget "http://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
script:
  - pytest --cov rfhub/ utests/KeywordTableTest.py -v --cov-config .coveragerc
  - robot -A tests/conf/default.args tests
  - robot -A tests/conf/postgres.args tests
after_success:
  - coveralls
